# Generated by Django 5.2.1 on 2025-05-27 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_challenge'),
        ('games', '0014_game_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenger_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='opponent_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gameitem'),
        ),
    ]
