# Generated by Django 5.2.1 on 2025-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_challenge_challenger_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameelo',
            name='elo',
            field=models.FloatField(default=0),
        ),
    ]
