# Generated by Django 5.2.1 on 2025-06-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_gameelo_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
