# Generated by Django 5.2.1 on 2026-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_challenge_points_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='loser_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner_notified',
            field=models.BooleanField(default=False),
        ),
    ]
