# Generated by Django 4.2 on 2026-05-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_game_modes'),
        ('accounts', '0007_challenge_loser_notified_challenge_winner_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamemode'),
        ),
        migrations.AddField(
            model_name='gameelo',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamemode'),
        ),
        migrations.AddConstraint(
            model_name='gameelo',
            constraint=models.UniqueConstraint(condition=models.Q(('mode__isnull', True)), fields=('user', 'game'), name='unique_game_elo_no_mode'),
        ),
        migrations.AddConstraint(
            model_name='gameelo',
            constraint=models.UniqueConstraint(condition=models.Q(('mode__isnull', False)), fields=('user', 'game', 'mode'), name='unique_game_elo_with_mode'),
        ),
    ]
