# Generated by Django 5.2.1 on 2026-05-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="stake_points",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="stake_settled",
            field=models.BooleanField(default=False),
        ),
    ]
