# Generated by Django 5.2.1 on 2025-05-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL del juego (ej: 'one-piece')", unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_icons/')),
                ('data_source_url', models.URLField(blank=True, help_text='URL de la API para sincronizar los datos', null=True)),
                ('field_mapping', models.JSONField(default=dict, help_text="Mapeo de campos: {'nombre': 'api_field'}")),
                ('defaults', models.JSONField(default=dict, help_text='Valores por defecto para campos faltantes')),
                ('attributes', models.JSONField(default=list, help_text='Lista de atributos que tiene cada ítem')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
