# Generated by Django 5.2.1 on 2025-05-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_numeric_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='data_source_url',
            new_name='api_url',
        ),
        migrations.AddField(
            model_name='game',
            name='api_detail_url_template',
            field=models.CharField(blank=True, help_text='Usa {url} si quieres inyectar la URL base', max_length=300, null=True),
        ),
    ]
