# Generated by Django 5.2.1 on 2025-05-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_data_source_url_game_api_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='api_url',
            new_name='data_source_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='api_detail_url_template',
        ),
    ]
