# Generated by Django 5.2.1 on 2025-05-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_api_url_game_data_source_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='defaults',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_mapping',
        ),
        migrations.AddField(
            model_name='game',
            name='attributes_raw',
            field=models.TextField(default='[]', verbose_name='Attributes (JSON array)'),
        ),
        migrations.AddField(
            model_name='game',
            name='defaults_raw',
            field=models.TextField(default='{}', verbose_name='Defaults (JSON)'),
        ),
        migrations.AddField(
            model_name='game',
            name='field_mapping_raw',
            field=models.TextField(default='{}', verbose_name='Field Mapping (JSON)'),
        ),
    ]
