# Generated by Django 5.2.1 on 2025-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_remove_game_attributes_remove_game_defaults_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='attributes_raw',
        ),
        migrations.RemoveField(
            model_name='game',
            name='defaults_raw',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_mapping_raw',
        ),
        migrations.AddField(
            model_name='game',
            name='attributes',
            field=models.JSONField(default=list, help_text='Lista de atributos que tiene cada ítem'),
        ),
        migrations.AddField(
            model_name='game',
            name='defaults',
            field=models.JSONField(default=dict, help_text='Valores por defecto para campos faltantes'),
        ),
        migrations.AddField(
            model_name='game',
            name='field_mapping',
            field=models.JSONField(default=dict, help_text="Mapeo de campos: {'nombre': 'api_field'}"),
        ),
    ]
