# Generated by Django 5.2.1 on 2025-05-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_gameresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='icon_image',
        ),
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_background/'),
        ),
    ]
