# Generated by Django 5.2.1 on 2025-05-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_image_game_icon_image_game_background_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['attempted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='gameresult',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='gameresult',
            name='games_gamer_game_id_6f916e_idx',
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='played_at',
            new_name='completed_at',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameitem'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='daily_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.dailytarget'),
        ),
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together={('user', 'daily_target')},
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='daily_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.dailytarget'),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='guess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameitem'),
        ),
        migrations.AddField(
            model_name='gameattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
