# Generated by Django 5.2.1 on 2025-05-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_dailytarget_gameattempt_alter_gameresult_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytarget',
            unique_together={('game', 'date')},
        ),
    ]
