# Generated by Django 5.2.1 on 2025-05-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_dailytarget_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytarget',
            name='date',
            field=models.DateField(),
        ),
    ]
