# Generated by Django 5.2.1 on 2025-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_dailytarget_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailytarget',
            name='is_team',
            field=models.BooleanField(default=False, help_text='¿Es un target de equipo?'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytarget',
            unique_together={('game', 'date', 'is_team')},
        ),
    ]
