# Generated by Django 5.2.1 on 2025-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_dailytarget_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='game_audios/'),
        ),
    ]
