# Generated by Django 5.2.1 on 2025-05-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_challenge_challenger_attempts_and_more'),
        ('games', '0014_game_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.challenge'),
        ),
        migrations.AlterField(
            model_name='gameattempt',
            name='daily_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.dailytarget'),
        ),
    ]
