# Generated by Django 5.2.1 on 2025-05-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_extradailyplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='extra_play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.extradailyplay'),
        ),
    ]
