# Generated by Django 5.2.1 on 2025-05-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_challenge_challenger_attempts_and_more'),
        ('games', '0017_gameattempt_extra_play'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.challenge'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='extra_play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.extradailyplay'),
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('user', 'daily_target'), name='unique_result_per_daily'),
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('user', 'extra_play'), name='unique_result_per_extra'),
        ),
        migrations.AddConstraint(
            model_name='gameresult',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_result_per_challenge'),
        ),
    ]
