# Generated by Django 5.2.1 on 2025-06-01 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_extradailyplay_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('DAILY', 'Daily'), ('EXTRA', 'Extra'), ('CHALLENGE', 'Challenge')], max_length=10)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='PK de DailyTarget / ExtraDailyPlay / Challenge', null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'session_type'], name='games_plays_game_id_274282_idx'), models.Index(fields=['user'], name='games_plays_user_id_4284c2_idx')],
                'unique_together': {('user', 'game', 'session_type', 'reference_id')},
            },
        ),
    ]
