# Generated by Django 5.2.1 on 2025-06-01 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_playsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.playsession'),
        ),
    ]
