# Generated by Django 5.2.1 on 2025-06-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_migrate_attempts_to_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(blank=True, default='#ff0000', max_length=7),
        ),
    ]
