# Generated by Django 5.2.1 on 2025-06-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_migrate_attempts_to_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameattempt',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='gameattempt',
            name='daily_target',
        ),
        migrations.RemoveField(
            model_name='gameattempt',
            name='extra_play',
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(help_text='1 = primer intento, 2 = segundo...')),
                ('points', models.PositiveIntegerField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='games.game')),
            ],
            options={
                'ordering': ('attempt_no',),
                'unique_together': {('game', 'attempt_no')},
            },
        ),
    ]
