# Generated by Django 5.2.1 on 2025-06-03 19:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_merge_0024_game_color_0025_seed_scoring_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
