# Generated by Django 5.2.1 on 2025-06-04 17:26

import apps.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_game_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='json_file',
            field=models.FileField(blank=True, help_text='Archivo JSON local para los datos del juego.', null=True, upload_to=apps.games.models.game_json_file_path),
        ),
    ]
