# Generated by Django 5.2.1 on 2025-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_alter_game_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
