# Generated by Django 5.2.1 on 2025-06-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_game_json_file'),
        ('games', '0028_gameitem_deleted_gameitem_deleted_at'),
    ]

    operations = [
    ]
