# Generated by Django 5.2.1 on 2025-06-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_merge_20250604_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='grouped_attributes',
            field=models.JSONField(default=list, help_text='Grupos de atributos a comparar conjuntamente (ej: [["tipo_1", "tipo_2"]])'),
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
