# Generated by Django 5.2.1 on 2025-06-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_game_grouped_attributes_delete_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='games.game')),
            ],
            options={
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GameItemModeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_data', to='games.gameitem')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_data', to='games.gamemode')),
            ],
            options={
                'unique_together': {('item', 'mode')},
            },
        ),
    ]
