# Generated by Django 5.2.1 on 2025-06-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_add_classic_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameattempt',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamemode'),
        ),
        migrations.AddField(
            model_name='playsession',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamemode'),
        ),
    ]
