# Generated by Django 4.2 on 2026-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_remove_dailytarget_legacy_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_mode_background/'),
        ),
    ]
