# Generated by Django 4.2 on 2026-05-30 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_lol_pasapalabra_mode(apps, schema_editor):
    Game = apps.get_model("games", "Game")
    GameMode = apps.get_model("games", "GameMode")
    game = (
        Game.objects.filter(slug="league-of-legends").first()
        or Game.objects.filter(slug="lol").first()
    )
    if not game:
        return
    max_sort = (
        GameMode.objects.filter(game=game).order_by("-sort_order").values_list("sort_order", flat=True).first()
        or 0
    )
    GameMode.objects.update_or_create(
        game=game,
        slug="pasapalabra",
        defaults={
            "label": "Pasapalabra",
            "play_type": "rosco",
            "sort_order": max_sort + 1,
            "item_filter": {},
            "active": True,
        },
    )


def unseed_lol_pasapalabra_mode(apps, schema_editor):
    Game = apps.get_model("games", "Game")
    GameMode = apps.get_model("games", "GameMode")
    game = (
        Game.objects.filter(slug="league-of-legends").first()
        or Game.objects.filter(slug="lol").first()
    )
    if game:
        GameMode.objects.filter(game=game, slug="pasapalabra", play_type="rosco").delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0038_playsession_surrendered'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoscoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
                ('question_type', models.CharField(choices=[('starts_with', 'Empieza por'), ('contains', 'Contiene la letra')], max_length=20)),
                ('prompt', models.TextField()),
                ('acceptable_answers', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosco_questions', to='games.game')),
            ],
            options={
                'ordering': ('letter', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WeeklyRosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Lunes ISO de la semana del rosco')),
                ('is_team', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_roscos', to='games.game')),
            ],
            options={
                'ordering': ('-week_start',),
            },
        ),
        migrations.AddField(
            model_name='gamemode',
            name='play_type',
            field=models.CharField(choices=[('wordle', 'Wordle'), ('rosco', 'Rosco')], default='wordle', max_length=10),
        ),
        migrations.AddField(
            model_name='playsession',
            name='rosco_current_letter',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='playsession',
            name='rosco_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'En curso'), ('failed', 'Fallida'), ('won_perfect', 'Victoria perfecta'), ('surrendered', 'Rendida')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='session_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('EXTRA', 'Extra'), ('CHALLENGE', 'Challenge'), ('ROSCO', 'Rosco')], max_length=10),
        ),
        migrations.CreateModel(
            name='WeeklyRoscoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('prompt_snapshot', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.roscoquestion')),
                ('weekly_rosco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='games.weeklyrosco')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='weeklyrosco',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_roscos', to='games.gamemode'),
        ),
        migrations.CreateModel(
            name='RoscoWeeklyPot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_amount', models.FloatField(default=0)),
                ('weekly_contribution', models.FloatField(default=0)),
                ('rollover_amount', models.FloatField(default=0)),
                ('settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('weekly_rosco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pot', to='games.weeklyrosco')),
            ],
        ),
        migrations.CreateModel(
            name='RoscoLetterAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
                ('answer_text', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosco_attempts', to='games.playsession')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoscoJackpotWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosco_jackpots', to='games.playsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosco_jackpots', to=settings.AUTH_USER_MODEL)),
                ('weekly_rosco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jackpot_winners', to='games.weeklyrosco')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weeklyroscoentry',
            constraint=models.UniqueConstraint(fields=('weekly_rosco', 'letter'), name='unique_weekly_rosco_letter'),
        ),
        migrations.AddConstraint(
            model_name='weeklyrosco',
            constraint=models.UniqueConstraint(fields=('game', 'mode', 'week_start', 'is_team'), name='unique_weekly_rosco'),
        ),
        migrations.AddIndex(
            model_name='roscoquestion',
            index=models.Index(fields=['game', 'letter', 'active'], name='games_rosco_game_id_09dd14_idx'),
        ),
        migrations.AddConstraint(
            model_name='roscoletterattempt',
            constraint=models.UniqueConstraint(fields=('session', 'letter'), name='unique_rosco_attempt_per_letter'),
        ),
        migrations.AddConstraint(
            model_name='roscojackpotwinner',
            constraint=models.UniqueConstraint(fields=('weekly_rosco', 'user'), name='unique_rosco_jackpot_winner_per_week'),
        ),
        migrations.RunPython(seed_lol_pasapalabra_mode, unseed_lol_pasapalabra_mode),
    ]
