# Generated by Django 4.2 on 2026-06-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_seed_league_of_legends_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='emoji_clues_revealed',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='play_type',
            field=models.CharField(choices=[('wordle', 'Wordle'), ('rosco', 'Rosco'), ('emoji', 'Emoji')], default='wordle', max_length=10),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='rosco_status',
            field=models.CharField(blank=True, choices=[('in_progress', 'En curso'), ('failed', 'Fallida'), ('completed', 'Completada'), ('won_perfect', 'Victoria perfecta'), ('surrendered', 'Rendida')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyrosco',
            name='week_start',
            field=models.DateField(help_text='Inicio del periodo de 7 días del rosco (desde el primer Pasapalabra)'),
        ),
        migrations.CreateModel(
            name='EmojiClueSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clues', models.JSONField(default=list, help_text='Lista de 3 a 6 pistas emoji en orden de revelado.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_clue_sets', to='games.game')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_clues', to='games.gameitem')),
            ],
            options={
                'ordering': ('item__name',),
            },
        ),
        migrations.AddConstraint(
            model_name='emojiclueset',
            constraint=models.UniqueConstraint(fields=('game', 'item'), name='unique_emoji_clue_set_per_item'),
        ),
    ]
