# Generated by Django 4.2 on 2026-06-07 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

POKEMON_SLUG = "pokemon"


def seed_silhouette_mode(apps, schema_editor):
    Game = apps.get_model("games", "Game")
    GameMode = apps.get_model("games", "GameMode")

    pokemon = Game.objects.filter(slug=POKEMON_SLUG).first()
    if not pokemon:
        return

    last = GameMode.objects.filter(game=pokemon).order_by("-sort_order").first()
    sort_order = (last.sort_order + 1) if last else 0
    GameMode.objects.update_or_create(
        game=pokemon,
        slug="silueta",
        defaults={
            "label": "Silueta",
            "play_type": "silhouette",
            "sort_order": sort_order,
            "item_filter": {},
            "active": True,
        },
    )


def unseed_silhouette_mode(apps, schema_editor):
    Game = apps.get_model("games", "Game")
    GameMode = apps.get_model("games", "GameMode")

    pokemon = Game.objects.filter(slug=POKEMON_SLUG).first()
    if not pokemon:
        return
    GameMode.objects.filter(game=pokemon, slug="silueta").delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0053_fix_whiskey_peak_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='play_type',
            field=models.CharField(choices=[('wordle', 'Wordle'), ('rosco', 'Rosco'), ('emoji', 'Emoji'), ('proximity', 'Proximidad'), ('silhouette', 'Silueta')], default='wordle', max_length=10),
        ),
        migrations.AlterField(
            model_name='playsession',
            name='session_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('EXTRA', 'Extra'), ('CHALLENGE', 'Challenge'), ('ROSCO', 'Rosco'), ('PROXIMITY', 'Proximity'), ('SILHOUETTE', 'Silhouette')], max_length=10),
        ),
        migrations.CreateModel(
            name='SilhouetteDailyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_team', models.BooleanField(default=False)),
                ('filter_config', models.JSONField(default=dict)),
                ('anchor', models.CharField(choices=[('tl', 'Top left'), ('tr', 'Top right'), ('bl', 'Bottom left'), ('br', 'Bottom right')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette_assignments', to='games.game')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette_assignments', to='games.gamemode')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette_assignments', to='games.gameitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='silhouettedailyassignment',
            constraint=models.UniqueConstraint(fields=('user', 'game', 'mode', 'date', 'is_team'), name='unique_silhouette_assignment_per_day'),
        ),
        migrations.RunPython(seed_silhouette_mode, unseed_silhouette_mode),
    ]
